# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1540, 886)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.download = QtWidgets.QPushButton(self.centralwidget)
        self.download.setGeometry(QtCore.QRect(1430, 800, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.download.setFont(font)
        self.download.setObjectName("download")
        self.keyword1 = QtWidgets.QTextEdit(self.centralwidget)
        self.keyword1.setGeometry(QtCore.QRect(130, 30, 1171, 43))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.keyword1.setFont(font)
        self.keyword1.setObjectName("keyword1")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(20, 30, 100, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.search = QtWidgets.QPushButton(self.centralwidget)
        self.search.setGeometry(QtCore.QRect(1320, 40, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.search.setFont(font)
        self.search.setObjectName("search")
        self.Abstract_1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.Abstract_1.setGeometry(QtCore.QRect(20, 190, 750, 601))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Abstract_1.setFont(font)
        self.Abstract_1.setObjectName("Abstract_1")
        self.label1_2 = QtWidgets.QLabel(self.centralwidget)
        self.label1_2.setGeometry(QtCore.QRect(40, 80, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label1_2.setFont(font)
        self.label1_2.setObjectName("label1_2")
        self.article_name = QtWidgets.QTextBrowser(self.centralwidget)
        self.article_name.setGeometry(QtCore.QRect(130, 80, 811, 43))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.article_name.setFont(font)
        self.article_name.setObjectName("article_name")
        self.label1_4 = QtWidgets.QLabel(self.centralwidget)
        self.label1_4.setGeometry(QtCore.QRect(960, 90, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label1_4.setFont(font)
        self.label1_4.setObjectName("label1_4")
        self.journal_gui = QtWidgets.QTextBrowser(self.centralwidget)
        self.journal_gui.setGeometry(QtCore.QRect(1070, 80, 441, 43))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.journal_gui.setFont(font)
        self.journal_gui.setObjectName("journal_gui")
        self.up = QtWidgets.QPushButton(self.centralwidget)
        self.up.setGeometry(QtCore.QRect(1260, 800, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.up.setFont(font)
        self.up.setObjectName("up")
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setGeometry(QtCore.QRect(1310, 800, 55, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.next.setFont(font)
        self.next.setObjectName("next")
        self.results_gui = QtWidgets.QLabel(self.centralwidget)
        self.results_gui.setGeometry(QtCore.QRect(1100, 800, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.results_gui.setFont(font)
        self.results_gui.setObjectName("results_gui")
        self.IF_3 = QtWidgets.QLabel(self.centralwidget)
        self.IF_3.setGeometry(QtCore.QRect(1080, 805, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.IF_3.setFont(font)
        self.IF_3.setObjectName("IF_3")
        self.num_gui = QtWidgets.QTextEdit(self.centralwidget)
        self.num_gui.setGeometry(QtCore.QRect(980, 800, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.num_gui.setFont(font)
        self.num_gui.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.num_gui.setObjectName("num_gui")
        self.label1_5 = QtWidgets.QLabel(self.centralwidget)
        self.label1_5.setGeometry(QtCore.QRect(20, 150, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label1_5.setFont(font)
        self.label1_5.setObjectName("label1_5")
        self.go = QtWidgets.QPushButton(self.centralwidget)
        self.go.setGeometry(QtCore.QRect(1370, 800, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.go.setFont(font)
        self.go.setObjectName("go")
        self.Abstract_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.Abstract_2.setGeometry(QtCore.QRect(780, 190, 750, 600))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Abstract_2.setFont(font)
        self.Abstract_2.setObjectName("Abstract_2")
        self.lable = QtWidgets.QLabel(self.centralwidget)
        self.lable.setGeometry(QtCore.QRect(1380, 140, 61, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lable.setFont(font)
        self.lable.setObjectName("lable")
        self.datebase_gui_2 = QtWidgets.QLabel(self.centralwidget)
        self.datebase_gui_2.setGeometry(QtCore.QRect(950, 140, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.datebase_gui_2.setFont(font)
        self.datebase_gui_2.setObjectName("datebase_gui_2")
        self.datebase_gui = QtWidgets.QTextBrowser(self.centralwidget)
        self.datebase_gui.setGeometry(QtCore.QRect(1070, 130, 301, 43))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.datebase_gui.setFont(font)
        self.datebase_gui.setObjectName("datebase_gui")
        self.year_gui = QtWidgets.QLabel(self.centralwidget)
        self.year_gui.setGeometry(QtCore.QRect(1450, 140, 61, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.year_gui.setFont(font)
        self.year_gui.setObjectName("year_gui")
        self.label1_6 = QtWidgets.QLabel(self.centralwidget)
        self.label1_6.setGeometry(QtCore.QRect(180, 140, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label1_6.setFont(font)
        self.label1_6.setObjectName("label1_6")
        self.author_gui = QtWidgets.QTextBrowser(self.centralwidget)
        self.author_gui.setGeometry(QtCore.QRect(260, 130, 681, 43))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.author_gui.setFont(font)
        self.author_gui.setObjectName("author_gui")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(14, 173, 104, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(720, 810, 241, 21))
        self.progressBar.setProperty("value", 100)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1540, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.keyword1, self.download)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.download.setText(_translate("MainWindow", "Download"))
        self.keyword1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label1.setText(_translate("MainWindow", "Keywords"))
        self.search.setText(_translate("MainWindow", "Serch"))
        self.Abstract_1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label1_2.setText(_translate("MainWindow", "Name"))
        self.article_name.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p dir=\'rtl\' style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt;\"><br /></p></body></html>"))
        self.label1_4.setText(_translate("MainWindow", "Journal"))
        self.up.setText(_translate("MainWindow", "Up"))
        self.next.setText(_translate("MainWindow", "Next"))
        self.results_gui.setText(_translate("MainWindow", "."))
        self.IF_3.setText(_translate("MainWindow", "/"))
        self.num_gui.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p dir=\'rtl\' style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1</p></body></html>"))
        self.label1_5.setText(_translate("MainWindow", "Abstract"))
        self.go.setText(_translate("MainWindow", "Go"))
        self.Abstract_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.lable.setText(_translate("MainWindow", "Year"))
        self.datebase_gui_2.setText(_translate("MainWindow", "Datebase"))
        self.year_gui.setText(_translate("MainWindow", "."))
        self.label1_6.setText(_translate("MainWindow", "Author"))
        self.author_gui.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p dir=\'rtl\' style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt;\"><br /></p></body></html>"))

