# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1390, 904)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout1.setSpacing(5)
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        self.label1.setMinimumSize(QtCore.QSize(120, 24))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(18)
        self.label1.setFont(font)
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName("label1")
        self.horizontalLayout1.addWidget(self.label1)
        self.keyword1 = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keyword1.sizePolicy().hasHeightForWidth())
        self.keyword1.setSizePolicy(sizePolicy)
        self.keyword1.setMinimumSize(QtCore.QSize(0, 49))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.keyword1.setFont(font)
        self.keyword1.setObjectName("keyword1")
        self.horizontalLayout1.addWidget(self.keyword1)
        self.search = QtWidgets.QPushButton(self.centralwidget)
        self.search.setMinimumSize(QtCore.QSize(80, 34))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.search.setFont(font)
        self.search.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.search.setObjectName("search")
        self.horizontalLayout1.addWidget(self.search)
        self.verticalLayout_3.addLayout(self.horizontalLayout1)
        self.horizontalLayout2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout2.setSpacing(5)
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.label1_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1_2.sizePolicy().hasHeightForWidth())
        self.label1_2.setSizePolicy(sizePolicy)
        self.label1_2.setMinimumSize(QtCore.QSize(50, 49))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label1_2.setFont(font)
        self.label1_2.setObjectName("label1_2")
        self.horizontalLayout2.addWidget(self.label1_2)
        self.article_name = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.article_name.sizePolicy().hasHeightForWidth())
        self.article_name.setSizePolicy(sizePolicy)
        self.article_name.setMinimumSize(QtCore.QSize(0, 49))
        self.article_name.setMaximumSize(QtCore.QSize(16777215, 49))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.article_name.setFont(font)
        self.article_name.setObjectName("article_name")
        self.horizontalLayout2.addWidget(self.article_name)
        self.label1_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1_4.sizePolicy().hasHeightForWidth())
        self.label1_4.setSizePolicy(sizePolicy)
        self.label1_4.setMinimumSize(QtCore.QSize(110, 49))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label1_4.setFont(font)
        self.label1_4.setObjectName("label1_4")
        self.horizontalLayout2.addWidget(self.label1_4)
        self.journal_gui = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.journal_gui.sizePolicy().hasHeightForWidth())
        self.journal_gui.setSizePolicy(sizePolicy)
        self.journal_gui.setMinimumSize(QtCore.QSize(300, 49))
        self.journal_gui.setMaximumSize(QtCore.QSize(16777215, 49))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.journal_gui.setFont(font)
        self.journal_gui.setObjectName("journal_gui")
        self.horizontalLayout2.addWidget(self.journal_gui)
        self.verticalLayout_3.addLayout(self.horizontalLayout2)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.horizontalLayout3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout3.setObjectName("horizontalLayout3")
        self.label1_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1_6.sizePolicy().hasHeightForWidth())
        self.label1_6.setSizePolicy(sizePolicy)
        self.label1_6.setMinimumSize(QtCore.QSize(80, 49))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label1_6.setFont(font)
        self.label1_6.setObjectName("label1_6")
        self.horizontalLayout3.addWidget(self.label1_6)
        self.author_gui = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.author_gui.sizePolicy().hasHeightForWidth())
        self.author_gui.setSizePolicy(sizePolicy)
        self.author_gui.setMinimumSize(QtCore.QSize(600, 49))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.author_gui.setFont(font)
        self.author_gui.setObjectName("author_gui")
        self.horizontalLayout3.addWidget(self.author_gui)
        self.datebase_gui_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datebase_gui_2.sizePolicy().hasHeightForWidth())
        self.datebase_gui_2.setSizePolicy(sizePolicy)
        self.datebase_gui_2.setMinimumSize(QtCore.QSize(120, 49))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.datebase_gui_2.setFont(font)
        self.datebase_gui_2.setObjectName("datebase_gui_2")
        self.horizontalLayout3.addWidget(self.datebase_gui_2)
        self.datebase_gui = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datebase_gui.sizePolicy().hasHeightForWidth())
        self.datebase_gui.setSizePolicy(sizePolicy)
        self.datebase_gui.setMinimumSize(QtCore.QSize(300, 49))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.datebase_gui.setFont(font)
        self.datebase_gui.setObjectName("datebase_gui")
        self.horizontalLayout3.addWidget(self.datebase_gui)
        self.lable = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lable.sizePolicy().hasHeightForWidth())
        self.lable.setSizePolicy(sizePolicy)
        self.lable.setMinimumSize(QtCore.QSize(80, 49))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lable.setFont(font)
        self.lable.setAlignment(QtCore.Qt.AlignCenter)
        self.lable.setObjectName("lable")
        self.horizontalLayout3.addWidget(self.lable)
        self.year_gui = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.year_gui.sizePolicy().hasHeightForWidth())
        self.year_gui.setSizePolicy(sizePolicy)
        self.year_gui.setMinimumSize(QtCore.QSize(100, 49))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.year_gui.setFont(font)
        self.year_gui.setObjectName("year_gui")
        self.horizontalLayout3.addWidget(self.year_gui)
        self.verticalLayout_3.addLayout(self.horizontalLayout3)
        self.horizontalLayout4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout4.setObjectName("horizontalLayout4")
        self.Abstract_1 = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(20)
        self.Abstract_1.setFont(font)
        self.Abstract_1.setObjectName("Abstract_1")
        self.horizontalLayout4.addWidget(self.Abstract_1)
        self.Abstract_2 = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Abstract_2.sizePolicy().hasHeightForWidth())
        self.Abstract_2.setSizePolicy(sizePolicy)
        self.Abstract_2.setMinimumSize(QtCore.QSize(600, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Abstract_2.setFont(font)
        self.Abstract_2.setObjectName("Abstract_2")
        self.horizontalLayout4.addWidget(self.Abstract_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout4)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 2)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 17))
        self.progressBar.setMaximumSize(QtCore.QSize(300, 16777215))
        self.progressBar.setProperty("value", 100)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 0, 1, 1)
        self.horizontalLayout5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout5.setSpacing(0)
        self.horizontalLayout5.setObjectName("horizontalLayout5")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout5.addWidget(self.line)
        self.num_gui = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_gui.sizePolicy().hasHeightForWidth())
        self.num_gui.setSizePolicy(sizePolicy)
        self.num_gui.setMinimumSize(QtCore.QSize(50, 40))
        self.num_gui.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std")
        font.setPointSize(18)
        self.num_gui.setFont(font)
        self.num_gui.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.num_gui.setObjectName("num_gui")
        self.horizontalLayout5.addWidget(self.num_gui)
        self.IF_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IF_3.sizePolicy().hasHeightForWidth())
        self.IF_3.setSizePolicy(sizePolicy)
        self.IF_3.setMaximumSize(QtCore.QSize(10, 16777215))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.IF_3.setFont(font)
        self.IF_3.setObjectName("IF_3")
        self.horizontalLayout5.addWidget(self.IF_3)
        self.results_gui = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.results_gui.sizePolicy().hasHeightForWidth())
        self.results_gui.setSizePolicy(sizePolicy)
        self.results_gui.setMinimumSize(QtCore.QSize(100, 34))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.results_gui.setFont(font)
        self.results_gui.setObjectName("results_gui")
        self.horizontalLayout5.addWidget(self.results_gui)
        self.up = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.up.sizePolicy().hasHeightForWidth())
        self.up.setSizePolicy(sizePolicy)
        self.up.setMinimumSize(QtCore.QSize(75, 34))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.up.setFont(font)
        self.up.setObjectName("up")
        self.horizontalLayout5.addWidget(self.up)
        self.next = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next.sizePolicy().hasHeightForWidth())
        self.next.setSizePolicy(sizePolicy)
        self.next.setMinimumSize(QtCore.QSize(75, 34))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.next.setFont(font)
        self.next.setObjectName("next")
        self.horizontalLayout5.addWidget(self.next)
        self.go = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.go.sizePolicy().hasHeightForWidth())
        self.go.setSizePolicy(sizePolicy)
        self.go.setMinimumSize(QtCore.QSize(75, 34))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.go.setFont(font)
        self.go.setObjectName("go")
        self.horizontalLayout5.addWidget(self.go)
        self.download = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.download.sizePolicy().hasHeightForWidth())
        self.download.setSizePolicy(sizePolicy)
        self.download.setMinimumSize(QtCore.QSize(110, 34))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.download.setFont(font)
        self.download.setObjectName("download")
        self.horizontalLayout5.addWidget(self.download)
        self.gridLayout.addLayout(self.horizontalLayout5, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1390, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.keyword1, self.download)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label1.setText(_translate("MainWindow", "Keywords"))
        self.keyword1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.search.setText(_translate("MainWindow", "Serch"))
        self.label1_2.setText(_translate("MainWindow", "Name"))
        self.article_name.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p dir=\'rtl\' style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label1_4.setText(_translate("MainWindow", "Journal"))
        self.label1_6.setText(_translate("MainWindow", "Author"))
        self.author_gui.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p dir=\'rtl\' style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt;\"><br /></p></body></html>"))
        self.datebase_gui_2.setText(_translate("MainWindow", "Datebase"))
        self.lable.setText(_translate("MainWindow", "Year"))
        self.year_gui.setText(_translate("MainWindow", "."))
        self.Abstract_1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Bahnschrift Light SemiCondensed\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Abstract_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.num_gui.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Adobe Heiti Std\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p dir=\'rtl\' style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">1</span></p></body></html>"))
        self.IF_3.setText(_translate("MainWindow", "/"))
        self.results_gui.setText(_translate("MainWindow", "."))
        self.up.setText(_translate("MainWindow", "Up"))
        self.next.setText(_translate("MainWindow", "Next"))
        self.go.setText(_translate("MainWindow", "Go"))
        self.download.setText(_translate("MainWindow", "Download"))

